baseURL = "http://purnimakamath.com/"
languageCode = "en-us"
title = "Purnima's blog"
theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Always a work in progress..."
enableGitalk = false
enableReadingTime = false
disableToC = true

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/gen-art"
name = "Generative Art"
weight = 4
[[menu.main]]
url = "/paintings"
name = "Paintings"
weight = 5
[[menu.main]]
url = "/blog"
name = "Blog"
weight = 2
[[menu.main]]
url = "/talks"
name = "Talks"
weight = 3
[[menu.main]]
url = "/"
name = "About"
weight = 1