baseURL = "https://purnimakamath.com"
languageCode = "en-us"
title = "Purnima's blog"
theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
subtitle = "Always a work in progress..."
enableGitalk = false
enableReadingTime = false
disableToC = true

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/gen-art/index.html"
name = "Generative Art"
weight = 4
[[menu.main]]
url = "/paintings/index.html"
name = "Paintings"
weight = 5
[[menu.main]]
url = "/blog/index.html"
name = "Blog"
weight = 2
[[menu.main]]
url = "/talks/index.html"
name = "Talks"
weight = 3
[[menu.main]]
url = "/about/me/index.html"
name = "About"
weight = 1

[deployment]
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "purnimakamath.com"

URL = "s3://purnimakamath.com?region=ap-southeast-1"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true